// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPZTPi8sD1e49LWfk4lnhkn3yhxa6XNc',
    appId: '1:256543906038:web:355a6d93c82e4a25b434d7',
    messagingSenderId: '256543906038',
    projectId: 'quiz-app-d8750',
    authDomain: 'quiz-app-d8750.firebaseapp.com',
    storageBucket: 'quiz-app-d8750.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX_OH3hbdVUbdqhQvgFcAjhbXDY_e0OCA',
    appId: '1:256543906038:android:af076a3a1c119d50b434d7',
    messagingSenderId: '256543906038',
    projectId: 'quiz-app-d8750',
    storageBucket: 'quiz-app-d8750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0jfIsB_TdD8aVsOc3rWS0r2n2QVTuoco',
    appId: '1:256543906038:ios:8a316cb9b1df1450b434d7',
    messagingSenderId: '256543906038',
    projectId: 'quiz-app-d8750',
    storageBucket: 'quiz-app-d8750.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0jfIsB_TdD8aVsOc3rWS0r2n2QVTuoco',
    appId: '1:256543906038:ios:8a316cb9b1df1450b434d7',
    messagingSenderId: '256543906038',
    projectId: 'quiz-app-d8750',
    storageBucket: 'quiz-app-d8750.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJPZTPi8sD1e49LWfk4lnhkn3yhxa6XNc',
    appId: '1:256543906038:web:c0a3aedcd9efb632b434d7',
    messagingSenderId: '256543906038',
    projectId: 'quiz-app-d8750',
    authDomain: 'quiz-app-d8750.firebaseapp.com',
    storageBucket: 'quiz-app-d8750.firebasestorage.app',
  );
}
