// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBiIKhrDicpMToN0shd3MRP2qkaV_y0A',
    appId: '1:675950705520:web:a717a6f85cba04c2ceadb5',
    messagingSenderId: '675950705520',
    projectId: 'quiz-app-ff1ef',
    authDomain: 'quiz-app-ff1ef.firebaseapp.com',
    storageBucket: 'quiz-app-ff1ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7wbwmyDuJxOK20ZfTT_4djqTB9odJDDM',
    appId: '1:675950705520:android:bae70c4469b11b1bceadb5',
    messagingSenderId: '675950705520',
    projectId: 'quiz-app-ff1ef',
    storageBucket: 'quiz-app-ff1ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9y118S_r0i0p3hRAaExWf3XEWuhrJws',
    appId: '1:675950705520:ios:b84ffc9d8b3530ceceadb5',
    messagingSenderId: '675950705520',
    projectId: 'quiz-app-ff1ef',
    storageBucket: 'quiz-app-ff1ef.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc9y118S_r0i0p3hRAaExWf3XEWuhrJws',
    appId: '1:675950705520:ios:b84ffc9d8b3530ceceadb5',
    messagingSenderId: '675950705520',
    projectId: 'quiz-app-ff1ef',
    storageBucket: 'quiz-app-ff1ef.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBiIKhrDicpMToN0shd3MRP2qkaV_y0A',
    appId: '1:675950705520:web:e7edb46d0a19dd4aceadb5',
    messagingSenderId: '675950705520',
    projectId: 'quiz-app-ff1ef',
    authDomain: 'quiz-app-ff1ef.firebaseapp.com',
    storageBucket: 'quiz-app-ff1ef.firebasestorage.app',
  );
}
